import fs from 'node:fs';
import path from 'node:path';

import { GeneratedFile } from '~/generate/file';

import { extractTriggers } from './extractor';
import type { TriggerExtractorPlugin } from './types';

/**
 * Generate TypeScript code for triggers output
 */
function generateTriggersCode(output: any): string {
  const lines: string[] = [];
  
  lines.push('// This file is auto-generated by @hey-api/trigger-extractor');
  lines.push('');
  
  // Type definitions
  lines.push('export type TriggerKind = "operation" | "webhook" | "callback" | "subscription" | "stream";');
  lines.push('');
  lines.push('export type TransportType = "sse" | "websocket" | "http";');
  lines.push('');
  lines.push('export interface AuthScheme {');
  lines.push('  type: "apiKey" | "http" | "oauth2" | "openIdConnect" | "mutualTLS";');
  lines.push('  name: string;');
  lines.push('  in?: "header" | "query" | "cookie";');
  lines.push('  scheme?: string;');
  lines.push('  bearerFormat?: string;');
  lines.push('  flows?: Record<string, any>;');
  lines.push('  openIdConnectUrl?: string;');
  lines.push('  description?: string;');
  lines.push('}');
  lines.push('');
  lines.push('export interface ServerInfo {');
  lines.push('  url: string;');
  lines.push('  description?: string;');
  lines.push('  variables?: Record<string, any>;');
  lines.push('}');
  lines.push('');
  lines.push('export interface Trigger {');
  lines.push('  id: string;');
  lines.push('  kind: TriggerKind;');
  lines.push('  method?: string;');
  lines.push('  path: string;');
  lines.push('  summary?: string;');
  lines.push('  description?: string;');
  lines.push('  tags?: string[];');
  lines.push('  servers?: ServerInfo[];');
  lines.push('  security?: string[][];');
  lines.push('  parameters?: {');
  lines.push('    path?: Record<string, any>;');
  lines.push('    query?: Record<string, any>;');
  lines.push('    header?: Record<string, any>;');
  lines.push('    cookie?: Record<string, any>;');
  lines.push('  };');
  lines.push('  requestBody?: any;');
  lines.push('  responses?: Record<string, any>;');
  lines.push('  subscriptionRegister?: string;');
  lines.push('  subscriptionCallback?: string;');
  lines.push('  transport?: TransportType;');
  lines.push('  extensions?: Record<string, any>;');
  lines.push('  original?: any;');
  lines.push('}');
  lines.push('');
  
  // Export the triggers array
  lines.push(`export const triggers: Trigger[] = ${JSON.stringify(output.triggers, null, 2)} as const;`);
  lines.push('');
  
  // Export byKind index
  lines.push(`export const byKind: Record<TriggerKind, Trigger[]> = ${JSON.stringify(output.byKind, null, 2)} as const;`);
  lines.push('');
  
  // Export authMap
  lines.push(`export const authMap: Record<string, AuthScheme> = ${JSON.stringify(output.authMap, null, 2)} as const;`);
  lines.push('');
  
  // Export meta
  lines.push(`export const meta = ${JSON.stringify(output.meta, null, 2)} as const;`);
  lines.push('');
  
  return lines.join('\n');
}

export const handler: TriggerExtractorPlugin['Handler'] = ({ plugin }) => {
  const spec = plugin.context.spec;
  const ir = plugin.context.ir;
  
  // Extract triggers from the spec
  const triggersOutput = extractTriggers(ir, spec);
  
  // Generate the TypeScript code as a string
  const code = generateTriggersCode(triggersOutput);
  
  // Write the file directly to disk since the symbol system doesn't support raw JSON data well
  const outputFileName = (plugin.config.output || 'triggers') + '.gen.ts';
  const fileNameWithoutExt = (plugin.config.output || 'triggers') + '.gen';
  const outputPath = path.resolve(plugin.context.config.output.path, outputFileName);
  
  // Ensure directory exists
  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  
  // Write the file
  if (!plugin.context.config.dryRun) {
    fs.writeFileSync(outputPath, code, 'utf-8');
  }
  
  // If exportFromIndex is enabled, schedule index update after all plugins have run
  if (plugin.config.exportFromIndex !== false && plugin.context.config.output.indexFile !== false) {
    // Use setTimeout to ensure this runs after the index file is created
    setTimeout(() => {
      const indexPath = path.resolve(plugin.context.config.output.path, 'index.ts');
      if (fs.existsSync(indexPath)) {
        let indexContent = fs.readFileSync(indexPath, 'utf-8');
        const exportStatement = `export * from './${fileNameWithoutExt}';`;
        // Add the export if it doesn't already exist
        if (!indexContent.includes(exportStatement)) {
          // Add it after the auto-generated comment
          indexContent = indexContent.trimEnd() + '\n' + exportStatement + '\n';
          fs.writeFileSync(indexPath, indexContent, 'utf-8');
        }
      }
    }, 100);
  }
};

export const handlerLegacy: TriggerExtractorPlugin['LegacyHandler'] = ({
  files,
  openApi,
  plugin,
}) => {
  const spec = plugin.context.spec;
  const ir = plugin.context.ir;
  
  // Extract triggers from the spec
  const triggersOutput = extractTriggers(ir, spec);
  
  // Create the output file
  const outputFileName = (plugin.config.output || 'triggers') + '.ts';
  const file = new GeneratedFile({
    dir: path.resolve(plugin.context.config.output.path),
    exportFromIndex: plugin.config.exportFromIndex ?? true,
    id: plugin.config.output || 'triggers',
    name: outputFileName,
  });
  
  // Generate the TypeScript code as a string
  const code = generateTriggersCode(triggersOutput);
  file.add(code);
  
  files[file.id] = file;
};
